-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- as per Hyprland wiki: hyprland-qt-support provides a QML style for hypr* qt6 apps                                                         

hl.config({
    ["plugin:hyprland-qt-support"] = {
        roundness = 2,
        border_width = 0,
        reduce_motion = false,
    }
})
