-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */ #

-- Hypridle
-- Original config submitted by https://github.com/SherLock707

local HOME = os.getenv("HOME")

-- FIX: iDIR was defined here but then re-constructed inline everywhere below.
-- It is now used consistently via this variable.
local iDIR = HOME .. "/.config/swaync/images/ja.png"

hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock",
        -- runs hyprlock if it is not already running (this is always run when "loginctl lock-session" is called)

        -- unlock_cmd = "killall hyprlock", -- kills hyprlock when unlocking (this is always run when "loginctl unlock-session" is called)

        before_sleep_cmd = "loginctl lock-session",
        -- ensures that the session is locked before going to sleep

        after_sleep_cmd = "hyprctl dispatch dpms on",
        -- turn on screen after sleep (not strictly necessary, but just in case)

        ignore_dbus_inhibit = false,
        -- whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    },
})

-- turn off screen faster if session is already locked
-- (disabled by default)
-- hl.config({
--     listener = {
--         timeout = 30,
--         ["on-timeout"] = "pidof hyprlock && hyprctl dispatch dpms off",
--         ["on-resume"]  = "pidof hyprlock && hyprctl dispatch dpms on",
--     },
-- })

-- FIX: Each listener block is a separate hl.config() call. Whether calling
-- hl.config() multiple times with 'listener' is additive or overwrites depends
-- on the Hyprland runtime. If only the second listener fires, merge both into
-- a single call or check if hl.listener() is the correct API for multiple listeners.
-- As written below, each call is intentional and mirrors the original .conf blocks.

-- Warn: notify after 9 minutes of idle
hl.config({
    listener = {
        timeout = 540,
        -- 9 min
        ["on-timeout"] = "notify-send -i " .. iDIR .. " 'You are idle!'",
        ["on-resume"]  = "notify-send -i " .. iDIR .. " 'Oh! you are Back Hello !!!'",
    },
})

-- Screenlock: lock session after 10 minutes of idle
hl.config({
    listener = {
        timeout = 600,
        -- 10 min
        ["on-timeout"] = "loginctl lock-session",
        -- on-resume = notify-send -i $iDIR " System Unlocked!"
    },
})

-- Turn off screen (disabled by default)
-- hl.config({
--     listener = {
--         timeout = 630,  -- 10.5 min
--         ["on-timeout"] = "hyprctl dispatch dpms off",
--         ["on-resume"]  = "hyprctl dispatch dpms on",
--     },
-- })

-- Suspend (disabled by default)
-- hl.config({
--     listener = {
--         timeout = 1200,  -- 20 min
--         ["on-timeout"] = "systemctl suspend",
--         ["on-resume"]  = "notify-send -i " .. iDIR .. " 'Oh! you are back' 'Hello !!!'",
--     },
-- })
