-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */ #

-- always refer to Hyprland wiki
-- https://wiki.hyprland.org/

-- Initial boot script enable to apply initial wallpapers, theming, new settings etc.
-- suggest not to change this or delete this including deleting referrence file in ~/.config/hypr/.initial_startup_done
-- as long as the referrence file is present, this initial-boot.sh will not execute

-- NOTE: All require() paths are relative to this file's location (~/.config/hypr/).
-- Each of these files must exist as a .lua file (not .conf) for require() to work.

-- Sourcing external config files

local HOME = os.getenv("HOME")

-- Default Configs directory path: ~/.config/hypr/configs/
require("configs/Keybinds")               -- Pre-configured keybinds

-- ## This is where you want to start tinkering

-- User Configs directory path: ~/.config/hypr/UserConfigs/
require("UserConfigs/Startup_Apps")       -- put your start-up packages on this file
require("UserConfigs/ENVariables")        -- Environment variables to load

--source= $UserConfigs/Monitors.conf # Its all about your monitor config (old dots) will remove on push to main
--source= $UserConfigs/WorkspaceRules.conf # Hyprland workspaces (old dots) will remove on push to main

require("UserConfigs/Laptops")            -- For laptop related
require("UserConfigs/LaptopDisplay")      -- Laptop display related. You need to read the comment on this file
require("UserConfigs/WindowRules")        -- all about Hyprland Window Rules and Layer Rules
require("UserConfigs/UserDecorations")    -- Decorations config file
require("UserConfigs/UserAnimations")     -- Animation config file
require("UserConfigs/UserKeybinds")       -- Put your own keybinds here
require("UserConfigs/UserSettings")       -- Main Hyprland Settings.
require("UserConfigs/01-UserDefaults")    -- settings for User defaults apps

-- nwg-displays
require("monitors")
require("workspaces")

-- Autostart
-- FIX: was hl.exec_cmd() which does not exist. The correct API is hl.dsp.exec_cmd().
hl.on("hyprland.start", function()
    hl.dsp.exec_cmd(HOME .. "/.config/hypr/initial-boot.sh")
end)
