-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Managed by TerminalMonitorSelector.sh

-- 2026-05-21 10:10:31 IST

hl.monitor({
    output   = "eDP-2",
    mode     = "disable",
    position = "auto",
    scale    = 1,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})
