-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Managed by TerminalMonitorSelector.sh

-- 2026-03-14 17:08:52 IST

hl.monitor({
    output   = "eDP-2",
    mode     = "2560x1600@240.0",
    position = "2831x1439",
    scale    = 1.0,
    bitdepth = 10,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@60.0",
    position = "3164x359",
    scale    = 1.0,
    bitdepth = 10,
})
