-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

--

-- # name "Minimal-2"

-- credit https://github.com/prasanthrangan/hyprdots

hl.config({
    animations = {
        enabled = true,
    },
})
