-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  

-- /* wallust template - colors-hyprland */ 

local background = "rgb(1E1E24)"
local foreground = "rgb(FEF2D3)"
local color0 = "rgb(45444B)"
local color1 = "rgb(1C182F)"
local color2 = "rgb(4F323D)"
local color3 = "rgb(613A47)"
local color4 = "rgb(814B4B)"
local color5 = "rgb(9B5853)"
local color6 = "rgb(BEA360)"
local color7 = "rgb(F6E4B7)"
local color8 = "rgb(AC9F80)"
local color9 = "rgb(25213E)"
local color10 = "rgb(694251)"
local color11 = "rgb(814D5F)"
local color12 = "rgb(AC6464)"
local color13 = "rgb(CE756E)"
local color14 = "rgb(FDD980)"
local color15 = "rgb(F6E4B7)"

return {
    background = background,
    foreground = foreground,
    color0 = color0,
    color1 = color1,
    color2 = color2,
    color3 = color3,
    color4 = color4,
    color5 = color5,
    color6 = color6,
    color7 = color7,
    color8 = color8,
    color9 = color9,
    color10 = color10,
    color11 = color11,
    color12 = color12,
    color13 = color13,
    color14 = color14,
    color15 = color15,
}

