-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- NOTE, THIS FILE IS BEING USED by disabling Laptop display monitor behaviour when closing lid.

-- See notes on Laptops.conf

-- hl.monitor({ name = "eDP-1", res = "preferred", pos = "auto", scale = 1 })
