-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- Commands & Programs to be executed at launch

local HOME = os.getenv("HOME")

local scriptsDir = HOME .. "/.config/hypr/scripts"

local UserScripts = HOME .. "/.config/hypr/UserScripts"

local wallDIR = HOME .. "/Pictures/wallpapers"

local lock = HOME .. "/.config/hypr/scripts/LockScreen.sh"

local AwwwRandom = HOME .. "/.config/hypr/UserScripts/WallpaperAutoChange.sh"

local livewallpaper = HOME .. "/Pictures/wallpapers/Sabrina Carpenter Kissing Screen Wallpaper.mp4"

-- wallust color
hl.on("hyprland.start", function()
    hl.exec_cmd("wallust run " .. HOME .. "/Pictures/wallpapers/")
end)

-- Startup
hl.on("hyprland.start", function()
    hl.exec_cmd("nm-applet --indicator")
end)

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
end)

hl.on("hyprland.start", function()
    hl.exec_cmd("swaync")
end)

hl.on("hyprland.start", function()
    hl.exec_cmd("blueman-applet")
end)

hl.on("hyprland.start", function()
    hl.exec_cmd("rog-control-center")
end)

hl.on("hyprland.start", function()
    hl.exec_cmd("ags")
end)

hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
end)

hl.on("hyprland.start", function()
    hl.exec_cmd("copyq --start-server")
end)

-- hl.on("hyprland.start", function()
--     hl.exec_cmd("kanshi")
-- end)

hl.on("hyprland.start", function()
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
end)

-- clipboard store text

hl.on("hyprland.start", function()
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)

-- clipboard store image

-- hl.on("hyprland.start", function()
--     hl.exec_cmd("pypr")
-- end)

-- Polkit (Note: Polkit setup varies, check the script)
hl.on("hyprland.start", function()
    hl.exec_cmd(HOME .. "/.config/hypr/scripts/Polkit.sh")
end)

-- Rainbow borders
-- hl.on("hyprland.start", function()
--     hl.exec_cmd(HOME .. "/.config/hypr/UserScripts/RainbowBorders.sh")
-- end)

-- Initial Wallpaper
hl.on("hyprland.start", function()
    hl.exec_cmd("swww-daemon --format xrgb")
end)

-- hl.on("hyprland.start", function()
--     hl.exec_cmd("sleep 0.5 && swww img " .. HOME .. "/Pictures/wallpapers/ja_wallpaper")
-- end)

-- Startup Apps
hl.on("hyprland.start", function()
    hl.exec_cmd("mattermost-desktop")
end)

hl.on("hyprland.start", function()
    hl.exec_cmd("zotero")
end)

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 24")
end)

hl.on("hyprland.start", function()
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'")
end)

hl.on("hyprland.start", function()
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-size 24")
end)
