-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- This is where you put your own keybinds. Be Mindful to check as well ~/.config/hypr/configs/Keybinds.conf to avoid conflict

-- if you think I should replace the Pre-defined Keybinds in ~/.config/hypr/configs/Keybinds.conf , submit an issue or let me know in DC and present me a valid reason as to why, such as conflicting with global shortcuts, etc etc

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more settings and variables

-- See also Laptops.conf for laptops keybinds 

-- /* ---- ✴️ Variables ✴️ ---- */  #

local HOME = os.getenv("HOME")

local mainMod = "SUPER"

local scriptsDir = HOME .. "/.config/hypr/scripts"

local UserScripts = HOME .. "/.config/hypr/UserScripts"

local UserConfigs = HOME .. "/.config/hypr/UserConfigs"

-- settings for User defaults apps - set your default terminal and file manager on this file
local user_defaults = require("UserConfigs/01-UserDefaults")
local term = user_defaults.term
local files = user_defaults.files

-- common shortcuts

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("pkill rofi || true && rofi -show drun -modi drun,filebrowser,run,window"))

-- Main Menu (APP Launcher)

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("xdg-open https://"))

-- default browser

--bind = $mainMod, A, exec, pkill rofi || true && ags -t 'overview' # desktop overview (if installed)

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.global("quickshell:overviewToggle"))

-- desktop overview (if installed)

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd(term))

--terminal

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd(files))

--file manager

-- Custom Shortcuts

hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("DRI_PRIME=0 VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json VK_LAYER_PATH=/usr/share/vulkan/explicit_layer.d google-chrome-stable --use-gl=desktop --enable-features=Vulkan --force-device-scale-factor=1.3"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "C", hl.dsp.exec_cmd("DRI_PRIME=0 VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json VK_LAYER_PATH=/usr/share/vulkan/explicit_layer.d google-chrome-stable --use-gl=desktop --enable-features=Vulkan --force-device-scale-factor=1.0"))

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("code --disable-gpu"))

hl.bind(mainMod .. " + " .. "A", hl.dsp.exec_cmd("antigravity"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "L", hl.dsp.exec_cmd("code --disable-gpu ."))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("systemctl poweroff"))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "M", hl.dsp.exec_cmd("nm-connection-editor"))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "N", hl.dsp.exec_cmd("blueman-manager"))

hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("systemctl reboot"))

hl.bind(mainMod .. " + " .. "Z", hl.dsp.exec_cmd("zotero"))

hl.bind(mainMod .. " + " .. "X", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/Toggle_audio.sh"))

hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("mattermost-desktop"))

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/TerminalMonitorSelector.sh"))

hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("cliphist list| rofi -dmenu| cliphist decode| wl-copy"))

hl.bind(mainMod .. " + " .. "I", hl.dsp.exec_cmd("~/.local/bin/connect_snowy_port_forwarding.sh"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "I", hl.dsp.exec_cmd("~/.local/bin/connect_snowy.sh"))

-- FEATURES / EXTRAS

hl.bind(mainMod .. " + " .. "H", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/KeyHints.sh"))

-- help / cheat sheet

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "R", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/Refresh.sh"))

-- Refresh waybar, swaync, rofi

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "E", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/RofiEmoji.sh"))

-- emoji menu

hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/RofiSearch.sh"))

-- Google search using rofi

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "O", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/ChangeBlur.sh"))

-- Toggle blur settings 

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "G", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/GameMode.sh"))

-- Toggle animations ON/OFF

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "L", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/ChangeLayout.sh"))

-- Toggle Master or Dwindle Layout

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "V", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/ClipManager.sh"))

-- Clipboard Manager

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "R", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/RofiThemeSelector.sh"))

-- KooL Rofi Menu Theme Selector

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("pkill rofi || true && " .. HOME .. "/.config/hypr/scripts/RofiThemeSelector-modified.sh"))

-- modified Rofi Theme Selector

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())

-- whole full screen

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "F", hl.dsp.window.fullscreen())

-- fake full screen

hl.bind(mainMod .. " + " .. "SPACE", hl.dsp.window.float())

--Float Mode

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "SPACE", hl.dsp.exec_cmd("hyprctl dispatch workspaceopt allfloat"))

--All Float Mode

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "Return", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/Dropterminal.sh " .. term))

-- Dropdown terminal

-- Desktop zooming or magnifier

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "mouse_down", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 2.0}')"))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "mouse_up", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 2.0}')"))

--# NOTES for ja (Hyprland version 0.39 (Ubuntu 24.04))

--bind = $mainMod ALT, mouse_down, exec, hyprctl keyword misc:cursor_zoom_factor "$(hyprctl getoption misc:cursor_zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 2.0}')"

--bind = $mainMod ALT, mouse_up, exec, hyprctl keyword misc:cursor_zoom_factor "$(hyprctl getoption misc:cursor_zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 2.0}')" 

-- Waybar / Bar related

hl.bind(mainMod .. " + " .. "CTRL + ALT" .. " + " .. "B", hl.dsp.exec_cmd("pkill -SIGUSR1 waybar"))

-- Toggle hide/show waybar 

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "B", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/WaybarStyles.sh"))

-- Waybar Styles Menu

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "B", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/WaybarLayout.sh"))

-- Waybar Layout Menu

-- FEATURES / EXTRAS (UserScripts)

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.exec_cmd(HOME .. "/.config/hypr/UserScripts/RofiBeats.sh"))

-- online music using rofi

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd(HOME .. "/.config/hypr/UserScripts/WallpaperSelect.sh"))

-- Select wallpaper to apply

hl.bind("CTRL + ALT" .. " + " .. "W", hl.dsp.exec_cmd(HOME .. "/.config/hypr/UserScripts/WallpaperEffects.sh"))

-- Wallpaper Effects by imagemagick

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd(HOME .. "/.config/hypr/UserScripts/WallpaperRandom.sh"))

-- Random wallpapers

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "O", hl.dsp.exec_cmd("hyprctl setprop active opaque toggle"))

-- disable opacity on active window

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/KeyBinds.sh"))

-- search keybinds via rofi

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "A", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/Animations.sh"))

--hyprland animations menu

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "O", hl.dsp.exec_cmd(HOME .. "/.config/hypr/UserScripts/ZshChangeTheme.sh"))

-- Change oh-my-zsh theme

hl.bind("ALT_L" .. " + " .. "SHIFT_L", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/SwitchKeyboardLayout.sh"), { locked = true, non_consuming = true })

-- Change keyboard layout globally

hl.bind("SHIFT_L" .. " + " .. "ALT_L", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/Tak0-Per-Window-Switch.sh"), { locked = true, non_consuming = true })

-- Change keyboard layout locally for each window

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "C", hl.dsp.exec_cmd(HOME .. "/.config/hypr/UserScripts/RofiCalc.sh"))

-- calculator (qalculate)

-- Move current workspaces to monitors (left right up or down)

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "F9", hl.dsp.exec_cmd("hyprctl dispatch movecurrentworkspacetomonitor l"))

--move current workspace to LEFT monitor

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "F10", hl.dsp.exec_cmd("hyprctl dispatch movecurrentworkspacetomonitor r"))

--move current workspace to RIGHT monitor

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "F11", hl.dsp.exec_cmd("hyprctl dispatch movecurrentworkspacetomonitor u"))

--move current workspace to UP monitor

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "F12", hl.dsp.exec_cmd("hyprctl dispatch movecurrentworkspacetomonitor d"))

--move current workspace to DOWN monitor

-- For passthrough keyboard into a VM

-- bind = $mainMod ALT, P, submap, passthru

--submap = passthru

-- to unbind

--bind = $mainMod ALT, P, submap, reset

--submap = reset
