-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

hl.config({
    animations = {
        enabled = true,
        bezier = {
            { name = "wind", x0 = 0.05, y0 = 0.9, x1 = 0.1, y1 = 1.05 },
            { name = "winIn", x0 = 0.1, y0 = 1.1, x1 = 0.1, y1 = 1.1 },
            { name = "winOut", x0 = 0.3, y0 = -0.3, x1 = 0, y1 = 1 },
            { name = "liner", x0 = 1, y0 = 1, x1 = 1, y1 = 1 },
            { name = "overshot", x0 = 0.05, y0 = 0.9, x1 = 0.1, y1 = 1.05 },
            { name = "smoothOut", x0 = 0.5, y0 = 0, x1 = 0.99, y1 = 0.99 },
            { name = "smoothIn", x0 = 0.5, y0 = -0.5, x1 = 0.68, y1 = 1.5 },
        },
        animation = {
            { name = "windows", enabled = 1, speed = 6, curve = "wind", style = "slide" },
            { name = "windowsIn", enabled = 1, speed = 5, curve = "winIn", style = "slide" },
            { name = "windowsOut", enabled = 1, speed = 3, curve = "smoothOut", style = "slide" },
            { name = "windowsMove", enabled = 1, speed = 5, curve = "wind", style = "slide" },
            { name = "border", enabled = 1, speed = 1, curve = "liner" },
            { name = "borderangle", enabled = 1, speed = 180, curve = "liner", style = "loop" },
            { name = "fade", enabled = 1, speed = 3, curve = "smoothOut" },
            { name = "workspaces", enabled = 1, speed = 5, curve = "overshot" },
            -- animations for -git or version >0.42.0
            { name = "workspacesIn", enabled = 1, speed = 5, curve = "winIn", style = "slide" },
            { name = "workspacesOut", enabled = 1, speed = 5, curve = "winOut", style = "slide" },
        },
    },
})

