-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
-- For window rules and layerrules
-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- Window Rules
-- browser tags
hl.windowrule({ name = "windowrule-1", tag = "+browser", match = { class = "^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)$" } })
hl.windowrule({ name = "windowrule-2", tag = "+browser", match = { class = "^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$" } })
hl.windowrule({ name = "windowrule-3", tag = "+browser", match = { class = "^(chrome-.+-Default)$" } })
hl.windowrule({ name = "windowrule-4", tag = "+browser", match = { class = "^([Cc]hromium)$" } })
hl.windowrule({ name = "windowrule-5", tag = "+browser", match = { class = "^([Mm]icrosoft-edge(-stable|-beta|-dev|-unstable))$" } })
hl.windowrule({ name = "windowrule-6", tag = "+browser", match = { class = "^(Brave-browser(-beta|-dev|-unstable)?)$" } })
hl.windowrule({ name = "windowrule-7", tag = "+browser", match = { class = "^([Tt]horium-browser|[Cc]achy-browser)$" } })
hl.windowrule({ name = "windowrule-8", tag = "+browser", match = { class = "^(zen-alpha|zen)$" } })

-- notif tags
hl.windowrule({ name = "windowrule-9", tag = "+notif", match = { class = "^(swaync-control-center|swaync-notification-window|swaync-client|class)$" } })

-- KooL settings tag
hl.windowrule({ name = "windowrule-10", tag = "+KooL_Cheat", match = { title = "^(KooL Quick Cheat Sheet)$" } })
hl.windowrule({ name = "windowrule-11", tag = "+KooL_Settings", match = { title = "^(KooL Hyprland Settings)$" } })
hl.windowrule({ name = "windowrule-12", tag = "+KooL-Settings", match = { class = "^(nwg-displays|nwg-look)$" } })

-- terminal tags
hl.windowrule({ name = "windowrule-13", tag = "+terminal", match = { class = "^(Alacritty|kitty|kitty-dropterm)$" } })

-- email tags
hl.windowrule({ name = "windowrule-14", tag = "+email", match = { class = "^([Tt]hunderbird|org.gnome.Evolution)$" } })
hl.windowrule({ name = "windowrule-15", tag = "+email", match = { class = "^(eu.betterbird.Betterbird)$" } })

-- project tags
hl.windowrule({ name = "windowrule-16", tag = "+projects", match = { class = "^(codium|codium-url-handler|VSCodium)$" } })
hl.windowrule({ name = "windowrule-17", tag = "+projects", match = { class = "^(VSCode|code-url-handler)$" } })
hl.windowrule({ name = "windowrule-18", tag = "+projects", match = { class = "^(jetbrains-.+)$" } })

-- screenshare tags
hl.windowrule({ name = "windowrule-19", tag = "+screenshare", match = { class = "^(com.obsproject.Studio)$" } })

-- IM tags
hl.windowrule({ name = "windowrule-20", tag = "+im", match = { class = "^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$" } })
hl.windowrule({ name = "windowrule-21", tag = "+im", center = true, float = true, size = "(monitor_w*0.6) (monitor_h*0.7)", match = { class = "^([Ff]erdium)$" } })
hl.windowrule({ name = "windowrule-22", tag = "+im", match = { class = "^([Ww]hatsapp-for-linux)$" } })
hl.windowrule({ name = "windowrule-23", tag = "+im", match = { class = "^(ZapZap|com.rtosta.zapzap)$" } })
hl.windowrule({ name = "windowrule-24", tag = "+im", match = { class = "^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$" } })
hl.windowrule({ name = "windowrule-25", tag = "+im", match = { class = "^(teams-for-linux)$" } })
hl.windowrule({ name = "windowrule-26", tag = "+im", match = { class = "^(im.riot.Riot|Element)$" } })

-- game tags
hl.windowrule({ name = "windowrule-27", tag = "+games", match = { class = "^(gamescope)$" } })
hl.windowrule({ name = "windowrule-28", tag = "+games", match = { class = "^(steam_app_\\d+)$" } })

-- gamestore tags
hl.windowrule({ name = "windowrule-29", tag = "+gamestore", match = { class = "^([Ss]team)$" } })
hl.windowrule({ name = "windowrule-30", tag = "+gamestore", match = { title = "^([Ll]utris)$" } })
hl.windowrule({ name = "windowrule-31", tag = "+gamestore", match = { class = "^(com.heroicgameslauncher.hgl)$" } })

-- file-manager tags
hl.windowrule({ name = "windowrule-32", tag = "+file-manager", match = { class = "^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt)$" } })
hl.windowrule({ name = "windowrule-33", tag = "+file-manager", match = { class = "^(app.drey.Warp)$" } })

-- wallpaper tags
hl.windowrule({ name = "windowrule-34", tag = "+wallpaper", match = { class = "^([Ww]aytrogen)$" } })

-- multimedia tags
hl.windowrule({ name = "windowrule-35", tag = "+multimedia", match = { class = "^([Aa]udacious)$" } })

-- multimedia-video tags
hl.windowrule({ name = "windowrule-36", tag = "+multimedia_video", match = { class = "^([Mm]pv|vlc)$" } })

-- settings tags
hl.windowrule({ name = "windowrule-37", tag = "+settings", center = true, match = { title = "^(ROG Control)$" } })
hl.windowrule({ name = "windowrule-38", tag = "+settings", match = { class = "^(wihotspot(-gui)?)$" } })
hl.windowrule({ name = "windowrule-39", tag = "+settings", match = { class = "^([Bb]aobab|org.gnome.[Bb]aobab)$" } })
hl.windowrule({ name = "windowrule-40", tag = "+settings", match = { class = "^(gnome-disks|wihotspot(-gui)?)$" } })
hl.windowrule({ name = "windowrule-41", tag = "+settings", match = { title = "(Kvantum Manager)" } })
hl.windowrule({ name = "windowrule-42", tag = "+settings", match = { class = "^(file-roller|org.gnome.FileRoller)$" } })
hl.windowrule({ name = "windowrule-43", tag = "+settings", match = { class = "^(nm-applet|nm-connection-editor|blueman-manager)$" } })
hl.windowrule({ name = "windowrule-44", tag = "+settings", center = true, match = { class = "^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$" } })
hl.windowrule({ name = "windowrule-45", tag = "+settings", match = { class = "^(qt5ct|qt6ct|[Yy]ad)$" } })
hl.windowrule({ name = "windowrule-46", tag = "+settings", match = { class = "(xdg-desktop-portal-gtk)" } })
hl.windowrule({ name = "windowrule-47", tag = "+settings", match = { class = "^(org.kde.polkit-kde-authentication-agent-1)$" } })
hl.windowrule({ name = "windowrule-48", tag = "+settings", match = { class = "^([Rr]ofi)$" } })

-- viewer tags
hl.windowrule({ name = "windowrule-49", tag = "+viewer", match = { class = "^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$" } })
hl.windowrule({ name = "windowrule-50", tag = "+viewer", match = { class = "^(evince)$" } })
hl.windowrule({ name = "windowrule-51", tag = "+viewer", match = { class = "^(eog|org.gnome.Loupe)$" } })

-- Some special override rules
hl.windowrule({ name = "windowrule-52", no_blur = true, opacity = 1.0, match = { tag = "multimedia_video*" } })

-- POSITION
hl.windowrule({ name = "windowrule-53", center = true, float = true, size = "(monitor_w*0.65) (monitor_h*0.9)", match = { tag = "KooL_Cheat*" } })
hl.windowrule({ name = "windowrule-54", center = true, float = true, match = { class = "([Tt]hunar)", title = "negative:(.*[Tt]hunar.*)" } })
hl.windowrule({ name = "windowrule-55", center = true, float = true, match = { tag = "KooL-Settings*" } })
hl.windowrule({ name = "windowrule-56", center = true, match = { title = "^(Keybindings)$" } })
hl.windowrule({ name = "windowrule-57", center = true, size = "(monitor_w*0.6) (monitor_h*0.7)", match = { class = "^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$" } })
hl.windowrule({ name = "windowrule-58", move = "((monitor_w*0.32)) ((monitor_h*0.07))", float = true, opacity = "0.95 0.75", pin = true, keep_aspect_ratio = true, match = { title = "^(Picture-in-Picture)$" } })

hl.windowrule({ name = "windowrule-59", idle_inhibit = "fullscreen", match = { fullscreen = 1 } })

-- windowrule move to workspace
hl.windowrule({ name = "windowrule-60", workspace = "1", match = { tag = "email*" } })
hl.windowrule({ name = "windowrule-61", workspace = "2", opacity = "0.9 0.8", match = { tag = "browser*" } })
hl.windowrule({ name = "windowrule-62", workspace = "5", match = { tag = "gamestore*" } })
hl.windowrule({ name = "windowrule-63", workspace = "7", opacity = "0.94 0.86", match = { tag = "im*" } })
hl.windowrule({ name = "windowrule-64", workspace = "8", no_blur = true, fullscreen = true, match = { tag = "games*" } })

-- windowrule move to workspace (silent)
hl.windowrule({ name = "windowrule-65", workspace = "4 silent", match = { tag = "screenshare*" } })
hl.windowrule({ name = "windowrule-66", workspace = "6 silent", match = { class = "^(virt-manager)$" } })
hl.windowrule({ name = "windowrule-67", workspace = "6 silent", match = { class = "^(.virt-manager-wrapped)$" } })
hl.windowrule({ name = "windowrule-68", workspace = "9 silent", opacity = "0.94 0.86", match = { tag = "multimedia*" } })

-- FLOAT
hl.windowrule({ name = "windowrule-69", float = true, opacity = "0.9 0.7", size = "(monitor_w*0.7) (monitor_h*0.7)", match = { tag = "wallpaper*" } })
hl.windowrule({ name = "windowrule-70", float = true, opacity = "0.8 0.7", size = "(monitor_w*0.7) (monitor_h*0.7)", match = { tag = "settings*" } })
hl.windowrule({ name = "windowrule-71", float = true, opacity = "0.82 0.75", match = { tag = "viewer*" } })
hl.windowrule({ name = "windowrule-72", float = true, match = { class = "([Zz]oom|onedriver|onedriver-launcher)$" } })
hl.windowrule({ name = "windowrule-73", float = true, match = { class = "(org.gnome.Calculator)", title = "(Calculator)" } })
hl.windowrule({ name = "windowrule-74", float = true, match = { class = "^(mpv|com.github.rafostar.Clapper)$" } })
hl.windowrule({ name = "windowrule-75", float = true, match = { class = "^([Qq]alculate-gtk)$" } })

-- windowrule - ######### float popups and dialogue #######
hl.windowrule({ name = "windowrule-76", float = true, center = true, match = { title = "^(Authentication Required)$" } })
hl.windowrule({ name = "windowrule-77", float = true, match = { class = "(codium|codium-url-handler|VSCodium)", title = "negative:(.*codium.*|.*VSCodium.*)" } })
hl.windowrule({ name = "windowrule-78", float = true, match = { class = "^(com.heroicgameslauncher.hgl)$", title = "negative:(Heroic Games Launcher)" } })
hl.windowrule({ name = "windowrule-79", float = true, match = { class = "^([Ss]team)$", title = "negative:^([Ss]team)$" } })
hl.windowrule({ name = "windowrule-80", float = true, size = "(monitor_w*0.7) (monitor_h*0.6)", center = true, match = { title = "^(Add Folder to Workspace)$" } })
hl.windowrule({ name = "windowrule-81", float = true, size = "(monitor_w*0.7) (monitor_h*0.6)", center = true, match = { title = "^(Save As)$" } })
hl.windowrule({ name = "windowrule-82", float = true, size = "(monitor_w*0.7) (monitor_h*0.6)", match = { initial_title = "(Open Files)" } })
hl.windowrule({ name = "windowrule-83", float = true, center = true, size = "(monitor_w*0.16) (monitor_h*0.12)", match = { title = "^(SDDM Background)$" } })

-- OPACITY
hl.windowrule({ name = "windowrule-84", opacity = "0.9 0.5", match = { tag = "projects*" } })
hl.windowrule({ name = "windowrule-85", opacity = "0.9 0.8", match = { tag = "file-manager*" } })
hl.windowrule({ name = "windowrule-86", opacity = "0.8 0.7", match = { tag = "terminal*" } })
hl.windowrule({ name = "windowrule-87", opacity = "0.8 0.7", match = { class = "^(gedit|org.gnome.TextEditor|mousepad)$" } })
hl.windowrule({ name = "windowrule-88", opacity = "0.9 0.8", match = { class = "^(deluge)$" } })
hl.windowrule({ name = "windowrule-89", opacity = "0.9 0.8", match = { class = "^(seahorse)$" } })

-- extras
hl.windowrule({ name = "windowrule-90", no_initial_focus = true, match = { class = "^(jetbrains-*)" } })
hl.windowrule({ name = "windowrule-91", no_initial_focus = true, match = { title = "^(wind.*)$" } })
hl.windowrule({ name = "windowrule-92", opacity = 0.9, match = { class = "^(code)$" } })

hl.windowrule({ name = "float-system-monitor", match = { class = "^(floating_top)$" }, float = true, center = true, opacity = "0.8 0.7", size = "(monitor_w*0.6) (monitor_h*0.6)" })
hl.windowrule({ name = "terminal-monitor-selector", match = { class = "^(terminal-monitor-selector)$" }, float = true, center = true, pin = true, opacity = "0.96 0.88", size = "(monitor_w*0.42) (monitor_h*0.34)" })

-- LAYER RULES
hl.layerrule({ name = "layerrule-1", blur = true, ignore_alpha = 0, match = { namespace = "rofi" } })
hl.layerrule({ name = "layerrule-2", blur = true, ignore_alpha = 0, match = { namespace = "notifications" } })
hl.layerrule({ name = "layerrule-3", blur = true, ignore_alpha = 0.5, match = { namespace = "quickshell:overview" } })
